### ISSUE TITLE
Is sasl needed in the application?

### ISSUE THREAD

**Issue by ctrlShiftBryan** [jlouis/fuse#16]
Do we really need to start sasl? Was this left in there intentionally?

**Comment by jlouis** [comment]
I think it is redundant and can be removed. To the best of my knowledge, we have no direct dependency on SASL.

**Comment by jlouis** [comment]
SASL *is* needed in this application. In `fuse_monitor` we call the `alarm_handler` to set/clear alarms when the fuse explodes. So we rely on a module in SASL for our correct operation, and thus we can't remove it from the dependency list.
