### ISSUE TITLE
update readme - users 

### ISSUE THREAD

**Issue by binarytemple-external** [jlouis/fuse#17]
> > The current code status is that we have extensive test cases and test frameworks written around the code, but it has not been used in production systems yet. If you use the system in production, I would very much like to hear about it. Especially if you encountered any problems while doing so.

Your project is used by [Yokozuna](https://github.com/basho/yokozuna/blob/2.0/rebar.config#L20) - part of Riak (which is quite a well known project).
- https://github.com/basho/yokozuna/blob/2.0/src/yz_fuse.erl
- https://github.com/basho/yokozuna/blob/2.0/src/yz_fuse_stats_sidejob.erl

Congrats!

**Comment by jlouis** [comment]
Awesome! I'll get this in. Thank you for mentioning this.

**Comment by jlouis** [comment]
Closed via 463989cee1ee279d830dc95c42711bde5afae08c

**Comment by binarytemple** [comment]
haha classic - there's a blast from the past. Oh Yokozuna, thou never truly stored or retrieved my lore.

**Comment by jlouis** [comment]
Necromancy is fun!
