### ISSUE TITLE
Fault Injection Fuses lead to errors

### ISSUE THREAD

**Issue by timbuchwaldt** [jlouis/fuse#28]
Hi!
I was just playing with the library and it seems like fault injection fuses lead to an internal error with the fuse monitor (Elixir Crashlog, nevermind the syntax:

```elixir
(fuse) src/fuse_monitor.erl:91: :fuse_monitor.update({Catalog.HTTPGateway, {:gradual, 0.002}}, [])
```

Looking at fuse_monitor.erl the error looks like a missing implementation of update for fault injection fuses.

**Comment by jlouis** [comment]
Oh, thank you for the bug report!

You are probably correct. I think that I've only tested those without the use of the monitor code in place. I'll let this Issue be a placeholder until the model gets updated with FI fuses in the monitor, which would solve this problem.

**Comment by davidsulc** [comment]
Any progress on this? Unless I'm mistaken, it would be fixed by changing `ok` to `_` on line 94 here: https://github.com/jlouis/fuse/blob/master/src/fuse_monitor.erl#L94

Would you like me to open a PR?

**Comment by jlouis** [comment]
Old bug, fix seems correct, so I've applied it to master.
