### ISSUE TITLE
gulp build issue with html files

### ISSUE THREAD

**Issue by giulianozorzi** [jlouis/fuse#29]
Hi,
I'm having troubles with gulp build.
I'va added a src/app/mystuff directory with a bunch of directives in it like

src/app/mystuff/directive1/directive1.controller.js
src/app/mystuff/directive1/directive1.hml
src/app/mystuff/directive1/directive1.module.js
src/app/mystuff/directive1/i18n/en.json

and so on

gulp build runs fine and outputs no errors but when I access the "compiled" website the browser tells me that directive1.html can't be found.
js files, scss files and json files are correctly copied/injected 

As a workaraound I've manually copied the html file in dist/app/mystuf/directive1/

Am I missing something basic ?

thanks a lot !

giuliano

**Comment by jlouis** [comment]
This seems to have went into the wrong repository. I'll just close it :)
