### ISSUE TITLE
Bump version and update hex.pm package

### ISSUE THREAD

**Issue by deadtrickster** [jlouis/fuse#33]
Thanks!

**Comment by deadtrickster** [comment]
you can push new version to hex.pm, please do? I see that after 2.4.0 tag it at least has my prometheus plugin (and that's my main interest).

**Comment by mrallen1** [comment]
OK. If @jlouis makes me an owner on hex then I can do it. Otherwise, I can't. But he could just do it himself if he went to all that trouble.

**Comment by jlouis** [comment]
I'll try getting this done tomorrow. It shouldn't be that hard to do :)

**Comment by jlouis** [comment]
There should now be a new hex.pm package. If something is amiss in that setup, please report back and I'll fix stuff:

https://hex.pm/packages/fuse

**Comment by mrallen1** [comment]
Awesome! Thank you!!
