### ISSUE TITLE
Project name isn't great

### ISSUE THREAD

**Issue by kxepal** [jlouis/fuse#4]
I'll open this issue because it's too oblivious (:

Reading announce on erlang-questions@ I wondering how all of those text is related to [FUSE](http://fuse.sourceforge.net/) and actually, the first and only association was: "Isn't this Erlang bindings to FUSE?" Like [fuserl](https://code.google.com/p/fuserl/) is. Google agrees with me on that: any "{language_name} fuse" request returns list of FUSE bindings on the top, so it would be hard to find your library (though it's looks very useful) like his name will confuse people who doesn't know about.

So may be it's a little bit late for name changes when 1.0.0 is released, but still is it possible to pick some more better name for the project?

**Comment by laheadle** [comment]
Any reason this is still open?

**Comment by jlouis** [comment]
Well, FUSE isn't gone yet :)

**Comment by paulo-ferraz-oliveira** [comment]
For me, Google'ing for "erlang fuse" yield first result as "https://github.com/jlouis/fuse", but I know Google is biased 😄.

**Comment by jlouis** [comment]
Ok, at least one issue can be closed today!
